---
- name: construir server web
  hosts: all
  become: yes
  tasks:
    - name: Instalar apache
      apt: 
        name: apache2 
        state: present
    - name: Arrancar el servicio Apache
      service: 
        name: apache2 
        state: started
